import { Link } from "react-router-dom";

export default function PrivacyPolicyPage() {
  return (
    <main className="auth-page">
      <section className="auth-card" style={{ maxWidth: 860 }}>
        <h1 className="auth-title">Privacy Policy</h1>
        <p className="auth-subtitle">Last updated: April 25, 2026</p>
        <p className="auth-subtitle">
          WorkControl is a private business application used to manage operational records such as
          maintenance clients, PDF reports, users, tools, vehicles, notifications and internal activity.
        </p>
        <p className="auth-subtitle">
          The application processes account information, client contact details, maintenance report data
          and files generated by authorized users. Gmail access, when granted, is used only to create email
          drafts requested by the user and attach generated PDF reports.
        </p>
        <p className="auth-subtitle">
          WorkControl does not sell personal data. Access is restricted to authorized users. Users can
          revoke Google access at any time from their Google Account permissions page.
        </p>
        <p className="auth-subtitle">
          For privacy questions, contact the WorkControl administrator at liftultau@gmail.com.
        </p>
        <div className="auth-actions" style={{ display: "flex", gap: 12, flexWrap: "wrap", marginTop: 20 }}>
          <Link className="secondary-btn" to="/">
            Home
          </Link>
          <Link className="primary-btn" to="/login">
            Login
          </Link>
        </div>
      </section>
    </main>
  );
}
