import {
  LayoutDashboard,
  User,
  Users,
  Wrench,
  CarFront,
  Package,
  FileText,
  Clock3,
  Briefcase,
  BarChart3,
  Bell,
  Settings,
  LogOut,
  CalendarDays,
  FileBadge2,
  TimerReset,
  BellRing,
  BadgeCheck,
  History,
  ArrowRight,
  CheckCircle2,
  AlertTriangle,
  ShieldAlert,
} from "lucide-react";

export const appIcons = {
  dashboard: LayoutDashboard,
  profile: User,
  users: Users,
  tools: Wrench,
  vehicles: CarFront,
  stock: Package,
  invoices: FileText,
  timesheets: Clock3,
  projects: Briefcase,
  reports: BarChart3,
  notifications: Bell,
  settings: Settings,
  logout: LogOut,

  calendar: CalendarDays,
  contracts: FileBadge2,
  workedHours: TimerReset,
  alerts: BellRing,
  employeeStatus: BadgeCheck,
  history: History,
  details: ArrowRight,
  success: CheckCircle2,
  warning: AlertTriangle,
  danger: ShieldAlert,
};